### ISSUE TITLE
ArrayIndexOutOfBoundsException on clean install

### ISSUE THREAD

**Issue by asarkar** [dsyer/spring-boot-startup-bench#8]
1. Clone
2. `./mvnw clean install`
3. Get coffee. Find build failed on return.
```
Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-jar-plugin:2.6:jar (default-jar) @ minimal ---
[WARNING] Error injecting: org.codehaus.plexus.archiver.jar.JarArchiver
java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
...
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.<clinit>(AbstractZipArchiver.java:116)
	... 96 more
[INFO] Reactor Summary:
[INFO] 
[INFO] spring-cloud-sample-configserver ................... SUCCESS [02:39 min]
[INFO] demo ............................................... SUCCESS [ 30.017 s]
[INFO] minimal ............................................ FAILURE [ 22.581 s]
```
macOS 10.13.3
```
$ java -version
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
```
```
$ docker --version
Docker version 18.03.0-ce, build 0520e24
```

**Comment by dsyer** [comment]
Works for me. 

```
$ java -version
openjdk version "1.8.0_152"
OpenJDK Runtime Environment (Zulu 8.25.0.1-linux64) (build 1.8.0_152-b16)
OpenJDK 64-Bit Server VM (Zulu 8.25.0.1-linux64) (build 25.152-b16, mixed mode)
```

Try updating your JDK? Clear the maven cache?

**Comment by asarkar** [comment]
Seems like the difference is Oracle vs OpenJDK?

**Comment by dsyer** [comment]
Works for me too with Oracle JDK. I guess there's something in your environment still.
